import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { ArticleService } from '../../services/article/article.service';
import { RoomService } from '../../services/room/room.service';
import { Artikl } from '../../models/artikl'; // Import the Artikl model
import { Prostorija } from '../../models/prostorija'; // Import the Prostorija model

@Component({
  selector: 'app-artikl-create-form',
  templateUrl: './artikl-create-form.component.html',
  styleUrls: ['./artikl-create-form.component.css'],
})
export class ArtiklCreateFormComponent implements OnInit {
  artiklForm: FormGroup;
  idProstorija!: number;
  selectedProstorija: Prostorija | undefined;

  constructor(
    private fb: FormBuilder,
    private router: Router,
    private route: ActivatedRoute,
    private artiklService: ArticleService,
    private prostorijaService: RoomService
  ) {
    this.artiklForm = this.fb.group({
      name: ['', Validators.required],
    });
  }

  ngOnInit(): void {
    // Extract the prostorijaId from route parameters
    this.route.paramMap.subscribe((params) => {
      const id = +params.get('idProstorija')!;
      if (id) {
        this.idProstorija = id;
        this.getProstorija(id);
      } else {
        console.error('Prostorija ID is missing from route parameters.');
        // Optionally, handle the missing ID case
      }
    });
  }

  getProstorija(id: number): void {
    this.prostorijaService.getProstorijaById(id).subscribe(
      (data: Prostorija) => {
        this.selectedProstorija = data;
      },
      (error: any) => {
        console.error('Error fetching prostorija:', error);
      }
    );
  }

  onSubmit(): void {
    if (this.artiklForm.valid && this.selectedProstorija) {
      const artiklData: Artikl = {
        idArtikl: 0, // Assuming idArtikl will be auto-generated by the backend
        name: this.artiklForm.value.name,
        prostorija: this.selectedProstorija,
      };

      this.artiklService.createArticle(artiklData).subscribe(
        (createdArtikl) => {
          console.log('Artikl created successfully:', createdArtikl);
          // Redirect to the relevant artikl form or list
          this.router.navigate(['/artikl-form', createdArtikl.idArtikl]);
        },
        (error) => {
          console.error('Failed to create artikl:', error);
          // Handle error if necessary
        }
      );
    } else {
      this.artiklForm.markAllAsTouched();
    }
  }
}
